export const masterAccounts = [
  "F.C. Tucker Company",
  "Southco, Inc.",
  "Smokey Bones",
  "G.I.S.",
  "S & K Sales Co.",
  "Go Auto",
  "BCD Meetings & Events",
  "Montrose Environmental Group",
  "Carter Machinery",
  "Flagger Force",
  "NAES",
  "Maples Group",
  "All My Sons Moving & Storage",
  "Grass Valley",
  "Aquatech",
  "Byrider",
  "SAGE Dining Services",
  "Health Sciences North/Horizon Sante-Nord",
  "J. J. Keller & Associates, Inc.",
  "Cheney Brothers, Inc.",
  "tms",
  "BDS Connected Solutions, LLC.",
  "Home Helpers Home Care",
  "InfoVision Inc.",
  "Nesco Resource",
  "Guardian Group",
  "ARUP Laboratories",
  "CubeSmart",
  "Belle Tire",
  "Bristow Group",
  "Equinox Gold Corp.",
  "United Bank",
  "The Office Gurus",
  "Burn Boot Camp",
  "Pillar To Post Home Inspectors",
  "Kraton Corporation",
  "Alamo Drafthouse Cinema",
  "Swire Coca-Cola, USA",
  "Younique Products",
  "Downtown Music",
  "Hilb Group",
  "BGE, Inc.",
  "Hylant",
  "Leaf Home",
  "AAON, Inc.",
  "Peak Support",
  "Blue Beacon Truck Washes",
  "Wilson Sonsini Goodrich & Rosati",
  "Price Industries",
  "Rehmann",
  "Cognex Corporation",
  "Surge Staffing",
  "Ainsworth Inc",
  "LM Restaurants",
  "Century Communities, Inc. (NYSE:CCS)",
  "Sage Hospitality Group",
  "Freudenberg Medical",
  "IT Convergence",
  "R+L Carriers",
  "GAT Airline Ground Support",
  "Reebok",
  "ODW Logistics",
  "JE Dunn Construction",
  "Inventus Power",
  "Austal USA",
  "The Boca Raton",
  "Myridius",
  "Kaiser Aluminum",
  "SIG SAUER, Inc.",
  "Autism Learning Partners",
  "Bison Transport Inc.",
  "UDR - Opening Doors to your future",
  "Enterprise Fleet Management",
  "Westat",
  "Gen Re",
  "Woodgrain",
  "Wheels Up",
  "Parks",
  "Interesting Engineering",
  "Corus Entertainment",
  "City Electric Supply",
  "BluePearl Pet Hospital",
  "Din Tai Fung North America",
  "Adtran",
  "STG Logistics",
  "Open Access BPO",
  "HOLT Group",
  "Althea",
  "Lawson Products",
  "The Vitamin Shoppe",
  "UFC GYM",
  "Harte Hanks",
  "Pride Global",
  "Alliance One",
  "Scooter's Coffee",
  "RDI Corporation",
  "Ferrellgas",
  "Seneca Foods Corporation",
  "Farm Bureau Financial Services",
  "Persimmon Homes"
] as const;
